buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

apply from: "android/variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
